=== FMate1/JR9KY7_XMLGyak/JR9KY7_0928/FM_kurzusfelvetel.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT FM_kurzusfelvetel (hallgato,kurzosok)>
	<!ATTLIST FM_kurzusfelvetel
		tanev CDATA #Required
		egyetem CDATA #Fixed "ME"
	>
	
<!ELEMENT hallgato(hnev,szulev,szak)>
	<!ATTLIST hallgato id CDATA #Required >
		<!ELEMENT hnev (#PCDATA)> 
		<!ELEMENT szulev (#PCDATA)>
		<!ELEMENT szak (#PCDATA)>

<!ELEMENT kurzusok(kurzus)>

<!ELEMENT kurzus(kurzusnev,kredit,hely,idopont,oktato)>
	<!ATTLIST kurzus id CDATA #REQUIRED>
		<!ELEMENT kurzusnev (#PCDATA)>
		<!ELEMENT kredit (#PCDATA)>
		<!ELEMENT hely (#PCDATA)>  
		<!ELEMENT idopont (#PCDATA)>  
		<!ELEMENT oktato (#PCDATA)>

=== FMate1/JR9KY7_XMLGyak/JR9KY7_1019/FM_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE FM_kurzusfelvetel SYSTEM "FM_kurzusfelvetel.dtd"> -->

<FM_kurzusfelvetel tanev="2022_2023 I." egyetem="ME">
	
	<hallgato id="JR9KY7.ME">
		<hnev>Fekete Máté</hnev>
		<szulev>2001-11-21</szulev>
		<szak evf="5">Mérnökinformatikus</szak>
	</hallgato>
	
	<kurzusok>
		<kurzus id="GEIAL322-B">
			<kurzusnev>Adatkezelés XML környezetben</kurzusnev>
			<kredit>5</kredit>
			<hely>XXXII.</hely>
			<idopont>Kedd 12:00-13:30</idopont>
			<oktato>Dr. Bednarik László</oktato>
		</kurzus>
		<kurzus id="GEIAL322-B">
			<kurzusnev>Adatbázisrendszerek I.</kurzusnev>
			<kredit>5</kredit>
			<hely>In101</hely>
			<idopont>Kedd 8:00-9:30</idopont>
			<oktato>Dr. Kovács László</oktato>
		</kurzus>
		<kurzus id="GEIAL322-B" nyelv="angol">
			<kurzusnev>Webalkalmazás fejlesztés-Java</kurzusnev>
			<kredit>5</kredit>
			<hely>In103</hely>
			<idopont>Csütörtök 8:00-9:30</idopont>
			<oktato>Dr. Barabás Péter</oktato>
		</kurzus>
	</kurzusok>
	
</FM_kurzusfelvetel>
